CREATE TABLE EMPLOYEE(
    ENO NUMBER(5)  PRIMARY KEY,
    ENAME VARCHAR(20) NOT NULL,
    DEPT VARCHAR(20) NOT NULL,
    BASIC NUMBER(10,2) CHECK (BASIC>= 5000 AND BASIC <= 45000)
);

INSERT INTO EMPLOYEE VALUES (101, 'RAMESH', 'FINANCE', 18000);
INSERT INTO EMPLOYEE VALUES (102, 'SURESH', 'ACCOUNTS', 25000);
INSERT INTO EMPLOYEE VALUES (103, 'GANESH', 'FINANCE', 30000);
INSERT INTO EMPLOYEE VALUES (104, 'MAHESH', 'HR', 15000);
INSERT INTO EMPLOYEE VALUES (105, 'KAMALESH', 'FINANCE', 40000);
INSERT INTO EMPLOYEE VALUES (106, 'SHREYA', 'FINANCE', 18000);
INSERT INTO EMPLOYEE VALUES (107, 'APOORVA', 'ACCOUNTS', 25000);
INSERT INTO EMPLOYEE VALUES (108, 'SHILPA', 'FINANCE', 30000);
INSERT INTO EMPLOYEE VALUES (109, 'AKANKSHA', 'HR', 15000);
INSERT INTO EMPLOYEE VALUES (110, 'PAMALA', 'FINANCE', 40000);

COMMIT;
ALTER TABLE EMPLOYEE ADD
(
    DA NUMBER,
    HRA NUMBER,
    GROSSPAY NUMBER,
    PF NUMBER,
    PT NUMBER,
    NETPAY NUMBER
);

UPDATE EMPLOYEE
SET DA =
CASE
    WHEN BASIC <= 20000 THEN BASIC * 0.80
    ELSE BASIC * 0.70
END;

UPDATE EMPLOYEE
SET HRA = BASIC * 0.10;

UPDATE EMPLOYEE
SET GROSSPAY = BASIC + DA + HRA;

UPDATE EMPLOYEE
SET PF = GROSSPAY * 0.12;


UPDATE EMPLOYEE
SET PT = GROSSPAY * 0.05;

UPDATE EMPLOYEE
SET NETPAY = GROSSPAY - (PF + PT);

COMMIT;

SELECT * FROM EMPLOYEE;

SELECT ENAME
FROM EMPLOYEE
WHERE DEPT='Finance';

SELECT ENAME
FROM EMPLOYEE
ORDER BY ENAME;

SELECT ENAME, NETPAY
FROM EMPLOYEE
ORDER BY NETPAY DESC;

SELECT *
FROM EMPLOYEE
WHERE NETPAY BETWEEN 15000 AND 35000;


SELECT ENAME, BASIC
FROM EMPLOYEE
WHERE ENAME LIKE '%th';


SELECT DEPT, COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY DEPT
HAVING COUNT(*) > 3;


DELETE FROM EMPLOYEE
WHERE DEPT='Accounts';

COMMIT;

SELECT * FROM EMPLOYEE;